/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unicundinamarca.modelos.persona;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jersson arley y santiago gomez
 */
//Panel principal
public class Panel extends javax.swing.JPanel {
    
    
    private Persona persona;
    private DefaultTableModel table_model_personas;
    
    
    DateFormat tf = DateFormat.getDateInstance();
    //constructor
    public Panel() {
        initComponents();
        button_eliminar.setVisible(false);
    }
    //metodo  del la tabla
    public void setTableModel(DefaultTableModel table_model_personas){
        this.table_model_personas = table_model_personas;
    }
    
    //refrescar la tabla
    public void refreshTableModel()
    {
        ArrayList<Persona> lista_personas = Repositorio.obtenerTodos();
        while (table_model_personas.getRowCount() > 0) {
            table_model_personas.removeRow(0);
        }
        
        for(Persona p : lista_personas)
        {
            String aux = p.getFechaNacimiento();
            String[] data = {Integer.toString(p.getId()), Integer.toString(p.getDocumento()), p.getNombre(), p.getApellido(), aux,Integer.toString(p.getEdad()),p.getTipoPersona()};
            table_model_personas.addRow(data);
        }
    }
    public String convertirFechaString(Date date){
	
        return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(date);
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_documento = new javax.swing.JLabel();
        text_documento = new javax.swing.JTextField();
        label_nombre = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        label_edad = new javax.swing.JLabel();
        text_edad = new javax.swing.JTextField();
        button_guardar = new javax.swing.JButton();
        button_buscar = new javax.swing.JButton();
        button_eliminar = new javax.swing.JButton();
        button_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        text_apellido = new javax.swing.JTextField();
        DC_fechaNacimiento = new com.toedter.calendar.JDateChooser();
        Label_fechaNacimiento = new javax.swing.JLabel();
        Label_persona = new javax.swing.JLabel();
        text_tipoPersona = new javax.swing.JTextField();

        label_documento.setText("Documento");

        text_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_documentoActionPerformed(evt);
            }
        });

        label_nombre.setText("Nombre");

        label_edad.setText("Edad");

        text_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_edadActionPerformed(evt);
            }
        });

        button_guardar.setText("Guardar");
        button_guardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_guardarActionPerformed(evt);
            }
        });

        button_buscar.setText("Buscar");
        button_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buscarActionPerformed(evt);
            }
        });

        button_eliminar.setBackground(new java.awt.Color(255, 102, 102));
        button_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        button_eliminar.setText("Eliminar");
        button_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_eliminarActionPerformed(evt);
            }
        });

        button_cancelar.setText("Cancelar");
        button_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Apellido");

        text_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_apellidoActionPerformed(evt);
            }
        });

        Label_fechaNacimiento.setText("fecha Nacimiento");

        Label_persona.setText("Tipo Persona");

        text_tipoPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tipoPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_edad)
                            .addComponent(label_nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(Label_fechaNacimiento)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DC_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_buscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_tipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_persona)
                            .addComponent(text_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_documento))
                        .addContainerGap(369, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_documento)
                    .addComponent(label_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_nombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_apellido)
                        .addComponent(text_documento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_edad)
                    .addComponent(Label_fechaNacimiento)
                    .addComponent(Label_persona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DC_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_guardar)
                    .addComponent(button_cancelar)
                    .addComponent(button_eliminar)
                    .addComponent(button_buscar))
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_documentoActionPerformed

    private void text_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_edadActionPerformed
//metodo para escuchar el boton
    private void button_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_guardarActionPerformed
       
        if( text_documento.getText().isEmpty() ||
            text_nombre.getText().isEmpty() ||
            text_edad.getText().isEmpty() ||
            text_apellido.getText().isEmpty() ||
            text_tipoPersona.getText().isEmpty()
        ){
            JOptionPane.showMessageDialog(this, "Por favor diligencie todo el formulario", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            //casos de los botones
            switch(evt.getActionCommand())
            {
                case "Guardar":
                    String fecha = Repositorio.convertirFechaString(DC_fechaNacimiento.getDate());
                    persona = Persona.crear(0, Integer.parseInt(text_documento.getText()), text_nombre.getText(), text_apellido.getText(), fecha,Integer.parseInt(text_edad.getText()), text_tipoPersona.getText());
                    Repositorio.crear(persona);
                    resetForm();
                    JOptionPane.showMessageDialog(this, "Persona creada satisfactoriamente", "Bien", JOptionPane.INFORMATION_MESSAGE);
                break;
                case "Editar":
                    persona.setDocumento(Integer.parseInt(text_documento.getText()));
                    persona.setNombre(text_nombre.getText());
                    persona.setApellido(text_apellido.getText());
                    persona.setFechaNacimiento(Repositorio.convertirFechaString(DC_fechaNacimiento.getDate()));
                    persona.setApellido(text_apellido.getText());
                    persona.setEdad(Integer.parseInt(text_edad.getText()));
                    persona.setTipoPersona(text_tipoPersona.getText());
                    Repositorio.editar(persona);
                    JOptionPane.showMessageDialog(this, "Persona actualizada satisfactoriamente", "Bien", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
            
            this.refreshTableModel();
            this.resetPersona();
        }
    }//GEN-LAST:event_button_guardarActionPerformed
//metodos  para los botones
    private void button_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buscarActionPerformed
        String documento = JOptionPane.showInputDialog(this, "Número de documento");
        if(!documento.isEmpty()){
            persona = Repositorio.buscar(documento);
            if(persona != null)
            {
                popularPersona(persona);
            }
        }
    }//GEN-LAST:event_button_buscarActionPerformed

    private void button_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelarActionPerformed
        resetPersona();
    }//GEN-LAST:event_button_cancelarActionPerformed

    private void button_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_eliminarActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Realmente desea eliminar esta persona", "Eliminar", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            Repositorio.eliminar(persona);
            this.refreshTableModel();
            this.resetPersona();
        }
    }//GEN-LAST:event_button_eliminarActionPerformed

    private void text_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_apellidoActionPerformed

    private void text_tipoPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tipoPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tipoPersonaActionPerformed
    //refescar todos los campos
    private void resetForm() {
        text_documento.setText("");
        text_nombre.setText("");
        text_edad.setText("");
        text_tipoPersona.setText("");
        text_apellido.setText("");
        DC_fechaNacimiento.setDate(null);
    }
    //resetear
    private void resetPersona() {
        persona.setId(0);
        persona.setDocumento(0);
        persona.setEdad(0);
        persona.setNombre("");
        persona.setTipoPersona("");
        persona.setApellido("");
        popularPersona(persona);
    }
    
    private void popularPersona(Persona persona) {
        text_documento.setText(Integer.toString(persona.getDocumento()));
        text_nombre.setText(persona.getNombre());
        text_edad.setText((Integer.toString(persona.getDocumento())));
        text_tipoPersona.setText(persona.getTipoPersona());
        text_apellido.setText(persona.getApellido());
        
        if(persona.getId() != 0){
            button_eliminar.setVisible(true);
            button_guardar.setActionCommand("Editar");
        } else {
            button_eliminar.setVisible(false);
            button_guardar.setActionCommand("Guardar");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DC_fechaNacimiento;
    private javax.swing.JLabel Label_fechaNacimiento;
    private javax.swing.JLabel Label_persona;
    private javax.swing.JButton button_buscar;
    private javax.swing.JButton button_cancelar;
    private javax.swing.JButton button_eliminar;
    private javax.swing.JButton button_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_documento;
    private javax.swing.JLabel label_edad;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JTextField text_apellido;
    private javax.swing.JTextField text_documento;
    private javax.swing.JTextField text_edad;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_tipoPersona;
    // End of variables declaration//GEN-END:variables
}
